# Generated by Django 4.2.7 on 2023-11-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("tag", models.CharField(max_length=7)),
                ("artist", models.CharField(max_length=226)),
                ("year", models.CharField(max_length=4)),
                ("views", models.IntegerField()),
                ("features", models.TextField()),
                ("lyrics", models.TextField()),
                ("language_cld3", models.CharField(max_length=3)),
                ("language_ft", models.CharField(max_length=3)),
                ("language", models.CharField(max_length=3)),
            ],
        ),
    ]
