# Generated by Django 4.2.7 on 2023-11-23 23:48

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0001_initial"),
    ]
    
    add_tsvector_col = """
    CREATE FUNCTION lang_code_to_lang_config(lang_code character varying) RETURNS regconfig
        LANGUAGE SQL
        IMMUTABLE
        RETURN
            CASE
                WHEN lang_code = 'es' THEN 'spanish'::regconfig
                WHEN lang_code = 'ca' THEN 'catalan'::regconfig
                WHEN lang_code = 'it' THEN 'italian'::regconfig
                WHEN lang_code = 'de' THEN 'german'::regconfig
                ELSE 'english'::regconfig
            END;
        ;

    ALTER TABLE songs_song 
        ADD COLUMN search_vector tsvector
            GENERATED ALWAYS AS (
                to_tsvector(lang_code_to_lang_config(language),
                    COALESCE(title, '') || ' ' ||
                    COALESCE(artist, '') || ' ' ||
                    COALESCE(lyrics, '')
                )
            )
        STORED;
    """

    remove_tsvector_col = """
        ALTER TABLE songs_song DROP COLUMN search_vector;
    """

    operations = [
        migrations.RunSQL(
            sql=add_tsvector_col,
            reverse_sql=remove_tsvector_col,
            state_operations=[
                migrations.AddField(
                    model_name="song",
                    name="search_vector",
                    field=django.contrib.postgres.search.SearchVectorField(null=True),
                ),
            ]
        ),
    ]
