# Generated by Django 4.2.7 on 2023-11-24 01:15

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0002_song_tsvector"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="song",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="song_ftsearch_idx"
            ),
        ),
    ]
